let articles = [
  {
    id: 0,
    name: "Vélo 1",
    img: "vélo1.webp",
    description: "Description du Vélo 1",
    price: 100,
    qte: 5,
    promo: true,
  },
  {
    id: 1,
    name: "Vélo 2",
    img: "vélo2.webp",
    description: "Description du Vélo 2",
    price: 200,
    qte: 3,
    promo: false,
  },
  {
    id: 2,
    name: "Vélo 3",
    img: "vélo3.webp",
    description: "Description du Vélo 3",
    price: 150,
    qte: 7,
    promo: true,
  },
  {
    id: 3,
    name: "Vélo 4",
    img: "vélo4.webp",
    description: "Description du Vélo 4",
    price: 250,
    qte: 2,
    promo: false,
  },
  {
    id: 4,
    name: "Vélo 5",
    img: "vélo5.webp",
    description: "Description du Vélo 5",
    price: 120,
    qte: 6,
    promo: true,
  },
  {
    id: 5,
    name: "Vélo 6",
    img: "vélo6.webp",
    description: "Description du Vélo 6",
    price: 220,
    qte: 4,
    promo: false,
  },
  {
    id: 6,
    name: "Vélo 7",
    img: "vélo7.webp",
    description: "Description du Vélo 7",
    price: 170,
    qte: 8,
    promo: true,
  },
  {
    id: 7,
    name: "Vélo 8",
    img: "vélo8.webp",
    description: "Description du Vélo 8",
    price: 230,
    qte: 1,
    promo: false,
  },
  {
    id: 8,
    name: "Vélo 9",
    img: "vélo9.webp",
    description: "Description du Vélo 9",
    price: 180,
    qte: 9,
    promo: true,
  },
  {
    id: 9,
    name: "Vélo 10",
    img: "vélo10.webp",
    description: "Description du Vélo 10",
    price: 240,
    qte: 10,
    promo: false,
  },
  // Ajoutez plus d'articles ici...
];

export { articles };
