let articles = [
  {
    id: 0,
    name: "Article 1",
    img: "vélo1.webp",
    description: "Description de l'article 1",
    price: 100,
    qte: 5,
    promo: true,
  },
  {
    id: 1,
    name: "Article 2",
    img: "vélo2.webp",
    description: "Description de l'article 2",
    price: 200,
    qte: 3,
    promo: false,
  },
  {
    id: 2,
    name: "Article 3",
    img: "vélo3.webp",
    description: "Description de l'article 3",
    price: 150,
    qte: 7,
    promo: true,
  },
  {
    id: 3,
    name: "Article 4",
    img: "vélo4.webp",
    description: "Description de l'article 4",
    price: 250,
    qte: 2,
    promo: false,
  },
  {
    id: 4,
    name: "Article 5",
    img: "vélo5.webp",
    description: "Description de l'article 5",
    price: 120,
    qte: 6,
    promo: true,
  },
  {
    id: 5,
    name: "Article 6",
    img: "vélo6.webp",
    description: "Description de l'article 6",
    price: 220,
    qte: 4,
    promo: false,
  },
  {
    id: 6,
    name: "Article 7",
    img: "vélo7.webp",
    description: "Description de l'article 7",
    price: 170,
    qte: 8,
    promo: true,
  },
  {
    id: 7,
    name: "Article 8",
    img: "vélo8.webp",
    description: "Description de l'article 8",
    price: 230,
    qte: 1,
    promo: false,
  },
  {
    id: 8,
    name: "Article 9",
    img: "vélo9.webp",
    description: "Description de l'article 9",
    price: 180,
    qte: 9,
    promo: true,
  },
  {
    id: 9,
    name: "Article 10",
    img: "vélo10.webp",
    description: "Description de l'article 10",
    price: 240,
    qte: 10,
    promo: false,
  },
  // Ajoutez plus d'articles ici...
];

export { articles };
